<a href="https://colab.research.google.com/github/Sushmitha9368/Sushmitha9368/blob/main/TAsk_20_NumPy_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.Create a 1D array using arange().**

Use the flip() function to reverse the order of elements in a 1D array.

Achieve the same above output without using flip().


In [ ]:
import numpy as np
arr=np.arange(1,11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#flip() function used to reverse the order of elements in an array
flip_arr=np.flip(arr)
print(flip_arr)
# same above output using flip
arr1=np.flip(flip_arr)
print(arr1)


[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]


**2.Create a boolean array indicating which elements of the above 1D array are greater than 3.**

* Replace all even numbers in the array with -1.


In [ ]:
print(arr)
bool=np.array(arr>3)
print(bool)
for i in range(len(arr)):
  if arr[i]%2==0:
    arr[i]=-1
print(arr)



[ 1  2  3  4  5  6  7  8  9 10]
[False False False  True  True  True  True  True  True  True]
[ 1 -1  3 -1  5 -1  7 -1  9 -1]


**3.Generate a 2D array with random elements.**

* Transpose the array.

* Flatten the array

* Include a value of 99 at index 2 in the above array.

* Add a value of 100 to the end of a given array.

* Delete the element at index 3 from the array.


In [ ]:
import numpy as np
arr=np.random.randint(1,5,size=(3,3))
print(arr)

[[2 1 3]
 [1 2 4]
 [1 1 2]]


In [ ]:
#Transpose the array
trans=np.transpose(arr)
print(trans)

[[2 1 1]
 [1 2 1]
 [3 4 2]]


In [ ]:
#Flatten the array
flat=arr.flatten()
print(flat)

[2 1 3 1 2 4 1 1 2]


In [ ]:
#replace 99 in 2nd index in above array
flat[2]=99
print(flat)

[  2   1  99   4   1   1   2 100 100]


In [ ]:
#Add a value of 100 to the end of a given array.
flat=np.append(flat,100)
print(flat)

[  2   1  99   4   1   1   2 100 100]


In [ ]:
#Delete the element at index 3 from the array.
flat=np.delete(flat,3)
print(flat)

[  2   1  99   4   1   1   2 100]


**4.Create a 2D array. Iterate through the elements of the array and print elements using both nditer() and for loop.**

* Generate two arrays with random float elements in it.

* perform all python operations (* + - / % //).

* Also apply all mathematical functions on the two arrays.


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
#Iterating elements using for loop
for i in arr:
  for j in i:
    print(j)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


In [ ]:
#Using nditer()
for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#Generate two arrays with random float elements in it
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print("First Array:",arr1)
print("Second Array:",arr2)

First Array: [[0.71270235 0.30905635 0.67209278]
 [0.64231055 0.31569685 0.45056336]
 [0.74984729 0.97037099 0.86530609]]
Second Array: [[0.42429217 0.7832853  0.16621338]
 [0.01845326 0.18180453 0.64822262]
 [0.6505906  0.99987327 0.2714345 ]]


In [ ]:
#perform all python operations (* + - / % //).
if arr1.shape==arr2.shape:
  print("Multiplication:",arr1*arr2)
  print("-------------")
  print("Addition:",arr1+arr2)
  print("-------------")
  print("Subtraction:",arr1-arr2)
  print("-------------")
  print("Division:",arr1/arr2)
  print("-------------")
  print("Modulus:",arr1%arr2)
  print("-------------")
  print("Floor Division:",arr1//arr2)
else:
  print("Arrays are not have same shape")

Multiplication: [[0.30239402 0.2420793  0.11171081]
 [0.01185273 0.05739512 0.29206536]
 [0.4878436  0.97024802 0.23487392]]
-------------
Addition: [[1.13699452 1.09234166 0.83830616]
 [0.66076381 0.49750138 1.09878597]
 [1.40043789 1.97024426 1.13674059]]
-------------
Subtraction: [[ 0.28841018 -0.47422895  0.50587941]
 [ 0.62385728  0.13389233 -0.19765926]
 [ 0.0992567  -0.02950227  0.59387159]]
-------------
Division: [[ 1.6797443   0.39456422  4.04355414]
 [34.80742236  1.73646311  0.69507504]
 [ 1.15256399  0.97049399  3.18790021]]
-------------
Modulus: [[0.28841018 0.30905635 0.00723928]
 [0.01489958 0.13389233 0.45056336]
 [0.0992567  0.97037099 0.0510026 ]]
-------------
Floor Division: [[ 1.  0.  4.]
 [34.  1.  0.]
 [ 1.  0.  3.]]


In [ ]:
#Also apply all mathematical functions on the two arrays.
#First Array
print("First Array:",arr1)
print("Sum:",np.sum(arr1))
print("Min:",np.min(arr1))
print("Max:",np.max(arr1))
print("Mean:",np.mean(arr1))
print("Median:",np.median(arr1))
print("Standard Deviation:",np.std(arr1))
print("Cum sum:",np.cumsum(arr1))
print("cum prod:",np.cumprod(arr1))
print("____________________")
print("Second Array:",arr2)
print("Sum:",np.sum(arr2))
print("Min:",np.min(arr2))
print("Max:",np.max(arr2))
print("Mean:",np.mean(arr2))
print("Median:",np.median(arr2))
print("Standard Deviation:",np.std(arr2))
print("Cum sum:",np.cumsum(arr2))
print("cum prod:",np.cumprod(arr2))







First Array: [[6 1 4]
 [8 3 9]
 [7 1 4]]
Sum: 43
Min: 1
Max: 9
Mean: 4.777777777777778
Median: 4.0
Standard Deviation: 2.739739556875101
Cum sum: [ 6  7 11 19 22 31 38 39 43]
cum prod: [     6      6     24    192    576   5184  36288  36288 145152]
____________________
Second Array: [[2 7 7]
 [6 9 7]
 [1 5 2]]
Sum: 46
Min: 1
Max: 9
Mean: 5.111111111111111
Median: 6.0
Standard Deviation: 2.6434171674156266
Cum sum: [ 2  9 16 22 31 38 39 44 46]
cum prod: [     2     14     98    588   5292  37044  37044 185220 370440]


**5.Create a random NumPy array. Generate mean, mode, median, variance and standard deviation of that array.**

In [ ]:
import numpy as np
import statistics
from scipy import stats
ran=np.random.randint(1,10,size=(3,3))
ran

array([[4, 7, 7],
       [6, 1, 8],
       [3, 8, 1]])

In [ ]:
print("Mean:",np.mean(ran))
print("Median:",np.median(ran))
print("Mode:",stats.mode(ran))
print("Variance:",np.var(ran))
print("Standered Deviation:",np.std(ran))

Mean: 5.0
Median: 6.0
Mode: ModeResult(mode=array([3, 1, 1]), count=array([1, 1, 1]))
Variance: 7.111111111111111
Standered Deviation: 2.6666666666666665


**6.Create two NumPy arrays of the same length with random numerical values. Compute the correlation coefficient between the two arrays**


In [ ]:
import numpy as np
ran1=np.random.rand(10)
ran2=np.random.rand(10)
correlation_matrix=np.corrcoef(ran1,ran2)
correlation_coefficient=correlation_matrix[0,1]
print(ran1)
print(ran2)
print("correlation coefficient:",correlation_coefficient)



[0.97861834 0.79915856 0.46147936 0.78052918 0.11827443 0.63992102
 0.14335329 0.94466892 0.52184832 0.41466194]
[0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
 0.61209572 0.616934   0.94374808 0.6818203 ]
correlation coefficient: 0.2137819059107341


**7.Create a 2x3 NumPy array with random integers. Multiply each column by a different scalar value without using a loop.**


In [ ]:
import numpy as np
arr=np.random.randint(1,11,size=(2,3))
print(arr)
scalar=np.array([2,4,6])
a=arr*scalar
print("Result:",a)

[[ 6  1  2]
 [ 6 10  4]]
Result: [[12  4 12]
 [12 40 24]]


**8.Create a NumPy array with shape (3, 3) filled with random values. Add a scalar value to each element in the array using broadcasting.**


In [ ]:
import numpy as np
arr=np.random.randint(1,10,(3,3))
print("Array:",arr)
#scalar=np.array([[[2,4,6],[1,5,7],[8,3,9]]])
scalar=np.random.randint(1,10,(3,3))
print("Scalar:",scalar)
print("Result:",arr+scalar)

Array: [[6 4 2]
 [9 1 5]
 [7 6 8]]
Scalar: [[9 9 3]
 [9 7 7]
 [2 7 9]]
Result: [[15 13  5]
 [18  8 12]
 [ 9 13 17]]


**9.Create two NumPy arrays with unique integer values. Find the intersection of the two sets using NumPy.**


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,5,6,7])
intersection=np.intersect1d(arr1,arr2)
print(intersection)


[2 3 5]


**10.Generate two NumPy arrays with integers. Calculate the set difference between the two arrays.**


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,5,6,7])
difference1=np.setdiff1d(arr1,arr2)
difference2=np.setdiff1d(arr2,arr1)
print(difference1)
print(difference2)


[1 4]
[6 7]
